version: 1
update_configs:
  - package_manager: "php:composer"
    directory: "/src"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:patch"